#!/usr/bin/env python3

import json
import datetime
import os
import curses
import argparse

HEIGHT = 250
WIDTH = 150
PADDING = (5,2)

def init(win):
    curses.init_pair(1,curses.COLOR_CYAN, curses.COLOR_BLACK)
    curses.init_pair(2,curses.COLOR_WHITE, curses.COLOR_CYAN)
    win.clear()
    win.attrset(curses.A_BOLD)
    win.attrset(curses.color_pair(1))

def draw_calander():
    calander_win = curses.newwin(HEIGHT, WIDTH, PADDING[1], curses.LINES - PADDING[0])
    calander_win.border()
    calander_win.refresh()

def draw_progress(upleft_point, view_upleft_point, view_rightbuttom_point):
    progress_pad = curses.newpad(curses.LINES - PADDING[1], WIDTH)
    progress_pad.border()
    progress_pad.refresh(upleft_point[1], upleft_point[0], view_upleft_point[1], view_upleft_point[0], view_rightbuttom_point[1], view_rightbuttom_point[0])

def draw_habits(upleft_point, view_upleft_point, view_rightbuttom_point):
    habits_pad = curses.newpad(curses.LINES - PADDING[1] - HEIGHT, WIDTH)
    habits_pad.border()
    habits_pad.refresh(upleft_point[1], upleft_point[0], view_upleft_point[1], view_upleft_point[0], view_rightbuttom_point[1], view_rightbuttom_point[0])

def main(main_win):
    init(main_win)
    draw_calander()
    #draw_habits((curses.LINES - WIDTH, curses.COLS - HEIGHT),(curses.COLS - WIDTH, curses.LINES - HEIGHT),(curses.COLS - PADDING[0], curses.LINES - PADDING[1]))
    #draw_progress((PADDING[0], PADDING[1]),(PADDING[0], PADDING[1]),(curses.COLS - WIDTH - PADDING[0], curses.LINES - PADDING[1]))
    main_win.refresh()
    main_win.getch()
curses.wrapper(main)
